/* eslint @typescript-eslint/no-var-requires: "off" */
const coachPic = require('./coach-pic.png').default;

const data = [
  {
    id: 1,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 2,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 3,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 4,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 5,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 6,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 7,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 8,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 9,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
  {
    id: 10,
    img: coachPic,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    categories: ["Life", "Career", "Executive"],
    languages: ["English", "Arabic"],
    experience: "5+",
    numooHours: "50+",
    rating: 4.9,
  },
];

export default data;