const data = [
  {
    id: 1,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    experience: 5,
    numooHours: 20,
    rating: 4.9,
  },
  {
    id: 2,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    experience: 5,
    numooHours: 20,
    rating: 4.9,
  },
  {
    id: 3,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    experience: 5,
    numooHours: 20,
    rating: 4.9,
  },
  {
    id: 4,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    experience: 5,
    numooHours: 20,
    rating: 4.9,
  },
  {
    id: 5,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    experience: 5,
    numooHours: 20,
    rating: 4.9,
  },
  {
    id: 6,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    experience: 5,
    numooHours: 20,
    rating: 4.9,
  },
  {
    id: 7,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    experience: 5,
    numooHours: 20,
    rating: 4.9,
  },
  {
    id: 8,
    name: "Awedis Keofteian",
    short: "Executive Manager",
    location: "Lebanon",
    price: "$50.00",
    tags: ["Art", "Paint", "Drawing", "Coding"],
    experience: 5,
    numooHours: 20,
    rating: 4.9,
  },
];

export default data;